name: Custom container action flow
on: [push]

jobs:
  hello-world-jobbe:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: glebtee/me-docker-container-action@536e277d08e31bd77472239a8f18f82fd3608b12
        with:
          greet: 'Booba the Octobattt'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"