name: Custom container action flow
on: [push]

jobs:
  hello-world-jobbe:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: glebtee/me-docker-container-action@8306d4a08785914abf62da45f41811bc8c2e90fb
        with:
          entryPoint: 'Booba the Octobattt'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"